version: '3.3'

services:
    postgres-db:
        image: postgres:14-alpine
        restart: 'no'
        environment:
            POSTGRES_USER: devices
            POSTGRES_PASSWORD: testpassword
            POSTGRES_DB: devices_menagement
        volumes:
          - postgres-db:/var/lib/postgresql
          #- ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
        ports:
          - 127.0.0.1:6000:5432
        healthcheck:
            test: ["CMD", "nc", "-z", "localhost:6000"]
            interval: 3s
            timeout: 1s
            retries: 3

volumes:
    postgres-db: