global using Xunit;
global using Authentication;
global using Moq;
global using Database.Models.Enums;
global using Database.Models;
global using Database.Repositories.Interfaces;
global using Microsoft.AspNetCore.Identity;
global using FluentAssertions;
global using Authentication.Jwt;